
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz - matches your existing config
    use_sim_time: false  # Important: Real hardware doesn't use sim time

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# ESP32 Hardware Interface Configuration
esp32_motor_controller:
  ros__parameters:
    # Hardware interface plugin
    plugin: my_slam_pkg/ESP32HardwareInterface
    
    # Hardware parameters - ADJUST THESE TO MATCH YOUR ROBOT
    wheel_radius: 0.05      # meters - from your URDF
    wheel_separation: 0.34  # meters - from your URDF
    
    # Communication topics
    cmd_vel_topic: /cmd_vel
    joint_states_topic: /joint_states
    
    # Joint configuration - must match URDF joint names
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    
    # Hardware simulation flag
    use_sim_hardware: false  # Set to true for testing without ESP32

# Differential Drive Controller Configuration
diff_drive_controller:
  ros__parameters:
    # Wheel assignments - matches your existing config
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
    
    # Physical parameters - CRITICAL: Must match your ESP32 robot exactly
    wheel_separation: 0.34  # meters - distance between left/right wheels
    wheel_radius: 0.05      # meters - wheel radius
    
    # Calibration multipliers - adjust these after testing
    wheel_separation_multiplier: 1.0   # Fine-tune rotation accuracy
    left_wheel_radius_multiplier: 1.0  # Fine-tune left wheel response
    right_wheel_radius_multiplier: 1.0 # Fine-tune right wheel response
    
    # Publishing configuration
    publish_rate: 50.0  # Hz
    
    # Frame configuration - must match your TF tree
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    
    # TF publishing
    enable_odom_tf: true
    
    # Topic configuration
    cmd_vel_topic: "cmd_vel"
    use_stamped_vel: false
    
    # Velocity limits - ADJUST BASED ON YOUR ROBOT'S CAPABILITIES
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5        # m/s - adjust for your motor specs
        min_velocity: -0.5       # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0    # m/s^2
        min_acceleration: -1.0   # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0        # rad/s - adjust for your robot
        min_velocity: -1.0       # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.0    # rad/s^2
        min_acceleration: -1.0   # rad/s^2
        
    # Odometry covariance - tune these based on your robot's accuracy
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Control mode
    open_loop: false
    
    # Wheel slip modeling
    wheel_slippage_factor: 0.05