slam_toolbox:
  ros__parameters:
    # === CRITICAL: Real hardware settings ===
    use_sim_time: false
    
    # === SLAM Mode for online mapping ===
    mode: mapping
    
    # === Frame Configuration ===
    base_frame: base_footprint
    map_frame: map
    odom_frame: odom
    
    # === Scan Topic ===
    scan_topic: /scan
    
    # === Transform Settings ===
    transform_publish_period: 0.02  # 50Hz
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    
    # === Map Settings ===
    map_update_interval: 2.0  # Update map every 2 seconds
    resolution: 0.05          # 5cm resolution
    map_publish_period: 1.0   # Publish map every second
    
    # === Scan Processing ===
    throttle_scans: 1         # Process every scan
    minimum_travel_distance: 0.1   # Minimum distance to update (meters)
    minimum_travel_heading: 0.1    # Minimum rotation to update (radians)
    minimum_time_interval: 0.2     # Minimum time between updates
    
    # === Laser Range Settings ===
    max_laser_range: 8.0      # RPLidar A1 max range
    min_laser_range: 0.15     # RPLidar A1 min range
    
    # === Scan Matching ===
    use_scan_matching: true
    use_scan_barycenter: true
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 8.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    
    # === Loop Closure ===
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 8
    loop_match_maximum_variance_coarse: 2.0
    loop_match_minimum_response_coarse: 0.3
    loop_match_minimum_response_fine: 0.4
    
    # === Optimization ===
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    optimization_delta: 0.05
    
    # === Interactive Mode ===
    enable_interactive_mode: true
    
    # === Pose Extrapolation ===
    use_pose_extrapolator: true
    
    # === Correlation Parameters ===
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.03
    
    # === Loop Search Parameters ===
    loop_search_space_dimension: 6.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    
    # === Distance and Angle Penalties ===
    distance_variance_penalty: 0.3
    angle_variance_penalty: 0.8
    
    # === Debug ===
    debug_logging: false