slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    
    # Frame Configuration - IMPORTANT: Must match EKF
    base_frame: base_footprint  # Same as EKF base_link_frame
    map_frame: map
    odom_frame: odom           # EKF publishes this frame
    
    # Scan Topic
    scan_topic: /scan
    
    # Transform Settings - Use EKF odometry
    transform_publish_period: 0.02  # 50Hz
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    
    # Map Settings
    map_update_interval: 1.5  # Faster updates with EKF
    resolution: 0.03          # Higher resolution 
    map_publish_period: 1.0
    
    # EKF-Enhanced Scan Processing
    throttle_scans: 1
    minimum_travel_distance: 0.03   # Reduced - EKF provides better odometry
    minimum_travel_heading: 0.03    # Reduced - EKF provides better odometry  
    minimum_time_interval: 0.1
    
    # Laser Range Settings
    max_laser_range: 8.0
    min_laser_range: 0.15
    
    # Enhanced Scan Matching with EKF
    use_scan_matching: true
    use_scan_barycenter: true
    scan_buffer_size: 15
    scan_buffer_maximum_scan_distance: 8.0
    link_match_minimum_response_fine: 0.05
    link_scan_maximum_distance: 1.0
    
    # Loop Closure (Enhanced with EKF)
    do_loop_closing: true
    loop_search_maximum_distance: 2.5
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 1.2
    loop_match_minimum_response_coarse: 0.4
    loop_match_minimum_response_fine: 0.5
    
    # Optimization (Faster with EKF assistance)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    optimization_delta: 0.03
    
    # Interactive Mode
    enable_interactive_mode: true
    
    # Pose Extrapolation (Enhanced with EKF)
    use_pose_extrapolator: true
    
    # Correlation Parameters (Tighter with EKF)
    correlation_search_space_dimension: 0.15
    correlation_search_space_resolution: 0.005
    correlation_search_space_smear_deviation: 0.02
    
    # Loop Search Parameters
    loop_search_space_dimension: 3.5
    loop_search_space_resolution: 0.03
    loop_search_space_smear_deviation: 0.02
    
    # Distance and Angle Penalties (Reduced with EKF)
    distance_variance_penalty: 0.15
    angle_variance_penalty: 0.3
    
    # Debug
    debug_logging: false