controller_manager:
  ros__parameters:
    update_rate: 50  # Higher update rate for smoother control
    use_sim_time: false  # Important: This needs to be false for real hardware

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Hardware configuration - this defines our ESP32 hardware interface
esp32_motor_controller:
  ros__parameters:
    use_sim_hardware: 'true'  # Set to 'true' for PC testing
    type: my_slam_pkg/ESP32HardwareInterface
    wheel_radius: 0.05      # Wheel radius from URDF - adjust to real hardware
    wheel_separation: 0.34  # Distance between left and right wheels - adjust to real hardware
    cmd_vel_topic: /cmd_vel  # Topic that the ESP32 listens to
    joint_states_topic: /joint_states  # Topic that the ESP32 publishes to
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint

diff_drive_controller:
  ros__parameters:
    # Configure the controller to use all four wheels
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
    
    # CRITICAL: Define wheel dimensions with precise values from real hardware
    wheel_separation: 0.34  # Distance between left and right wheels
    wheel_radius: 0.05      # Wheel radius
    
    # ROTATION FIX: Adjust these multipliers to fine-tune rotation behavior
    wheel_separation_multiplier: 1.05  # Slightly increased to improve rotation accuracy
    left_wheel_radius_multiplier: 0.95  # Reduce left wheel effective radius
    right_wheel_radius_multiplier: 0.95 # Reduce right wheel effective radius
    
    # Higher publishing rate for smoother visualization
    publish_rate: 50.0
    
    # Important: These frames must match navigation stack
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    
    # Critical setting: MUST be true for visualization
    enable_odom_tf: true
    
    # Topic configuration - used by twist_mux
    cmd_vel_topic: "cmd_vel"
    use_stamped_vel: false
    
    # Velocity limits - adjust based on real hardware capabilities
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5   # Adjust to real hardware max speed
        min_velocity: -0.5  # Adjust to real hardware max speed
        has_acceleration_limits: true
        max_acceleration: 1.0  # Adjust to real hardware capability
        min_acceleration: -1.0  # Adjust to real hardware capability
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0   # Adjust to real hardware max turning rate
        min_velocity: -1.0  # Adjust to real hardware max turning rate
        has_acceleration_limits: true
        max_acceleration: 1.0  # Adjust to real hardware capability
        min_acceleration: -1.0  # Adjust to real hardware capability
        
    # Pose covariance diagonal values for odom (adjust to reduce drift)
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Twist covariance diagonal values for odom (adjust to reduce drift)
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Enable open loop control for more predictable rotation
    open_loop: false
    
    # Improved wheel slip modeling - adjust for real world surface
    wheel_slippage_factor: 0.05