slam_toolbox:
  ros__parameters:
    # SLAM Mode
    mode: mapping
    
    # Robot frame params
    base_frame: base_footprint
    map_frame: map
    odom_frame: odom
    
    # Scan matching params
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.15
    link_scan_maximum_distance: 1.5
    
    # Loop closure params
    loop_search_space_dimension: 9.0
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.4
    loop_match_minimum_response_fine: 0.5
    
    # Optimization params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    optimization_delta: 0.05
    optimization_step_size: 0.5
    
    # Visualization params
    enable_interactive_mode: true
    
    # General params
    use_pose_extrapolator: true
    debug_logging: false
    throttle_scans: 1
    transform_timeout: 0.2
    map_update_interval: 5.0
    resolution: 0.05
    # تم تعديل نطاق الليدار
    max_laser_range: 8.0  
    min_laser_range: 0.15  # تم تخفيض الحد الأدنى
    minimum_time_interval: 0.5
    transform_publish_period: 0.02
    map_publish_period: 2.0
    # Fine-tuning parameters
    resolution: 0.03  # Increased resolution (smaller value)
    transform_publish_period: 0.05  # More frequent transforms
    map_update_interval: 2.0  # More frequent map updates

    # Correlation parameters
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.03

    # Distance and angle penalties
    distance_variance_penalty: 0.3
    angle_variance_penalty: 0.8


    