twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: /cmd_vel
        timeout: 0.5
        priority: 10
      teleop:
        topic: /teleop_cmd_vel
        timeout: 0.5
        priority: 100
    
    # Output topic for the merged command velocity
    publisher:
      topic: /diff_drive_controller/cmd_vel_unstamped
